[package]
name = "command_reminder"
version = "0.1.0"
authors = ["Dean Johnson <dean@deanljohnson.com>"]
edition = "2018"

[dependencies]
clap = "~2.32"
dirs = "1.0.4"
nix = "0.9.0"
error-chain = "0.12.0"